### PR TITLE
Update Common configuration

### PR DESCRIPTION
**Pull request by olivierodo**
In order to share more configuration between the repositories of the Organization im proposing to centralized:

- [x]  Issue template (using the new issue template form feature)
- [x] Pull Request template
- [x] Github action workflow template
- [x] FUNDING.md
- [ ] CONTRIBUTING.md
- [x] CODE_OF_CONDUCT.md
- [ ] ~~SECURITY.md~~
- [x] SUPPORT.md
- [x] LICENSE

> documentation: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

I also added the lint checker for the link into markdowns.

### CODE REVIEW

**Comment by olivierodo** [comment]
I cross security out, i think it will required a bit more research to understand the benefits and how to write it properly for the overall organization

**Comment by olivierodo** [comment]
Regarding the CONTRIBUTING.md, i believe we should have brainstorming about the overall developer experience that we want to provide

**Review by tony-go — APPROVED** [review]
LGTM 🚀

**Comment by tony-go** [comment]
> I cross security out, i think it will required a bit more research to understand the benefits and how to write it properly for the overall organization

Let's take a slot this week!

**Pull request merged**
